name: Push to release branch

on:
  push:
    branches:
      - chain4travel
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  release:
    name: Release
    needs: [ci]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Create .npmrc
        run: echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' >> .npmrc
      - name: Install dependencies
        run: yarn install
      - name: Build library
        run: yarn build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCH: chain4travel
        run: yarn run semantic-release
